name: Chronos Frontend Image
id: chronos-fe
stages:
  - id: build
    base: node:lts
    singlelayer: false
    labels:
      maintainer: Vanilla OS Contributors
    entrypoint: ["npm", "run", "publish"]
    expose: 
      "6090": ""
    modules:
      - name: build-app
        type: shell
        source:
          type: git
          url: https://github.com/Vanilla-OS/chronos-frontend
          branch: main
          commit: latest
        commands:
          - mv /sources/build-app /app
          - cd /app
          - npm install
          - npm run build
