name: Chronos Frontend Image
id: chronos-fe
stages:
  - id: build
    base: node:lts
    singlelayer: false
    labels:
      maintainer: Vanilla OS Contributors
    entrypoint:
      exec:
        - /bin/sh
        - '-c'
        - cd /app && pnpm run publish
    expose:
      "6090": ""
    modules:
      - name: pnpm
        type: shell
        commands:
          - corepack enable pnpm
          - corepack use pnpm@latest-10

      - name: build-app
        type: shell
        source:
          type: git
          url: https://github.com/Vanilla-OS/chronos-frontend
          branch: main
          commit: latest
        commands:
          - mv /sources/build-app /app
          - cd /app
          - pnpm install
          - pnpm build
